[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'out'
libs = ['lib']
no_match_path = "contracts/*"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 1
viaIR = false
gas_limit = 9223372036854775807
eth_rpc_url = "YOUR_RPC_URL"
fs_permissions = [{ access = "read", path = "./"}]

[profile.ci_test]
fork_block_number = 18963715

[profile.ci_sizes]
optimizer_runs = 1
test = 'DO_NOT_COMPILE'

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
runs = 1
max_test_rejects = 9_999_999
